### ISSUE TITLE
Crash when processing docs for Rust 0.10-pre HEAD

### ISSUE THREAD

**Issue by esummers** [indirect/dash-rust#1]
rustdoc has undergone many changes lately.  Looks like one of them broke dash-rust.

```
mkdir -p Rust.docset/Contents/Resources
cp icon.png Rust.docset/
cp Info.plist Rust.docset/Contents/
Enter the path to the local rust docs
/Users/esummers/Documents/Rust/github/rust/doc/
cp -r /Users/esummers/Documents/Rust/github/rust/doc/ Rust.docset/Contents/Resources/Documents
Indexing arena...
Indexing collections...
Indexing extra...
Indexing flate...
Indexing fourcc...
Indexing getopts...
Indexing glob...
Indexing green...
Indexing native...
Indexing num...
Indexing rustdoc...
Indexing rustuv...
Indexing semver...
Indexing serialize...
Indexing std...
rake aborted!
undefined method `gsub!' for nil:NilClass
/Users/esummers/Documents/Rust/github/dash-rust/lib/docset_index.rb:110:in `block in add'
/Users/esummers/Documents/Rust/github/dash-rust/lib/docset_index.rb:110:in `each'
/Users/esummers/Documents/Rust/github/dash-rust/lib/docset_index.rb:110:in `add'
/Users/esummers/Documents/Rust/github/dash-rust/lib/docset_index.rb:89:in `block (2 levels) in index_docs_search_indexes'
/Users/esummers/Documents/Rust/github/dash-rust/lib/docset_index.rb:66:in `each'
/Users/esummers/Documents/Rust/github/dash-rust/lib/docset_index.rb:66:in `block in index_docs_search_indexes'
/Users/esummers/Documents/Rust/github/dash-rust/lib/docset_index.rb:54:in `each'
/Users/esummers/Documents/Rust/github/dash-rust/lib/docset_index.rb:54:in `index_docs_search_indexes'
/Users/esummers/Documents/Rust/github/dash-rust/lib/docset_index.rb:25:in `save'
/Users/esummers/Documents/Rust/github/dash-rust/Rakefile:46:in `block in <top (required)>'
Tasks: TOP => default => docset => docset:index => Rust.docset/Contents/Resources/docSet.dsidx
(See full trace by running task with --trace)
```

**Comment by indirect** [comment]
Dash now ships with a nicer docset than mine, but only for Rust 0.9. Maybe we can cooperate with Kapeli directly to get a 10.0 docset?

In the meantime, I'm happy to accept pull requests, or I'll fix this when I get the chance.

**Comment by esummers** [comment]
Thanks.  It would be nice to have a docset generator for third party rlibs.  I'll reach out to Kapeli.

I was able to make your script work by changing line 110 to:

```
[name, type, path].each{|arg| arg.to_s.gsub!("'", "''") }
```

Everything looks fine in the output as far as I can tell.

**Comment by esummers** [comment]
More accurately type is nil for Macros.  Probably since 0.9 didn't include Macros in the documentation.

```
["log", nil, "std/macros/macro.log.html"]
["error", nil, "std/macros/macro.error.html"]
["warn", nil, "std/macros/macro.warn.html"]
["info", nil, "std/macros/macro.info.html"]
["debug", nil, "std/macros/macro.debug.html"]
["log_enabled", nil, "std/macros/macro.log_enabled.html"]
["fail", nil, "std/macros/macro.fail.html"]
["assert", nil, "std/macros/macro.assert.html"]
["assert_eq", nil, "std/macros/macro.assert_eq.html"]
["unreachable", nil, "std/macros/macro.unreachable.html"]
["unimplemented", nil, "std/macros/macro.unimplemented.html"]
["format", nil, "std/macros/macro.format.html"]
["write", nil, "std/macros/macro.write.html"]
["writeln", nil, "std/macros/macro.writeln.html"]
["print", nil, "std/macros/macro.print.html"]
["println", nil, "std/macros/macro.println.html"]
["local_data_key", nil, "std/macros/macro.local_data_key.html"]
["try", nil, "std/macros/macro.try.html"]
["vec", nil, "std/macros/macro.vec.html"]
["select", nil, "std/macros/macro.select.html"]
```

This also works:

```
[name, type.to_s, path].each{|arg| arg.gsub!("'", "''") }
```

Talked to Kapeli.  They have no plans to release a docset generator or provide anything other then docsets for releases.  Ideally librustdoc should probably be used to generate the docsets directly.  Maybe if I get motivated...

EDIT: More info.

**Comment by esummers** [comment]
This is a better fix:

```
  DASH_TYPE = {
    "enum" => "Enum",
    "ffi" => "Function",
    "fn" => "Function",
    "method" => "Method",
    "mod" => "Module",
    "static" => "Constant",
    "struct" => "Class",
    "structfield" => "Attribute",
    "trait" => "Trait",
    "tymethod" => "Method",
    "typedef" => "Type",
    "variant" => "Option",
    "macro" => "Macro"
  }
```
